apiVersion: k3d.io/v1alpha2 
kind: Simple 
name: k3d-lab
servers: 1 
agents: 3
image: rancher/k3s:v1.20.4-k3s1 
ports:
  - port: 30000:30000
    nodeFilters:
      - agent[0]
  - port: 30001:30001
    nodeFilters:
      - agent[0]
options:
  k3d: 
    wait: true 
    timeout: "60s" 
    disableLoadbalancer: true
    disableImageVolume: false 
    disableHostIPInjection: false 
  k3s: 
    extraServerArgs: 
      - --no-deploy=traefik
  kubeconfig:
    updateDefaultKubeconfig: true 
    switchCurrentContext: true 
