---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: corpora-source
spec:
  type: git
  params:
    - name: url
      value: https://github.com/muokid3/k3d-lab
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: corpora-image
spec:
  type: image
  params:
    - name: url
      value: docker.io/muokid3/corpora:lab
