install:
	@make -C ingress install
	@make -C logging install
	@make -C monitoring install
	@make -C pipelines install


delete:
	@make -C ingress delete
	@make -C logging delete
	@make -C monitoring delete
	@make -C pipelines delete